# Generated by Django 2.2.7 on 2019-12-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20191201_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinform',
            name='kakao_id',
            field=models.CharField(default='DEFAULT_KAKAO_ID', max_length=10),
        ),
        migrations.AlterField(
            model_name='userinform',
            name='nickname',
            field=models.CharField(max_length=16),
        ),
    ]
