# Generated by Django 2.2.7 on 2019-11-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('auth_code', models.CharField(max_length=10)),
                ('auth_status', models.BooleanField()),
            ],
        ),
    ]
