# Generated by Django 2.2.7 on 2019-12-01 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailauth',
            options={'verbose_name_plural': 'EmailAuth'},
        ),
    ]
