# Generated by Django 2.2.7 on 2019-12-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0002_auto_20191201_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailauth',
            name='auth_ip',
            field=models.CharField(default='127.0.0.1', max_length=20),
        ),
    ]
