# Generated by Django 2.2.7 on 2019-12-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0003_emailauth_auth_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailauth',
            name='auth_ip',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
