# Generated by Django 3.0 on 2019-12-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.IntegerField()),
                ('guest_id', models.IntegerField()),
                ('bookmark', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('mute', models.BooleanField(default=False)),
            ],
        ),
    ]
