# Generated by Django 2.2.7 on 2019-12-01 05:13

from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('host_id', models.ForeignKey(on_delete=models.CASCADE, to='User.User')),
                ('guest_id', models.ForeignKey(on_delete=models.CASCADE, to='User.User')),
                ('bookmark', models.BooleanField(null=True)),
                ('hidden', models.BooleanField(null=True)),
                ('mute', models.BooleanField(null=True)),
            ],
        ),
    ]