# Generated by Django 2.2.7 on 2019-12-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='FriendLists',
            options={'verbose_name_plural': 'FriendLists'},
        ),
    ]
