# Generated by Django 2.2.7 on 2019-12-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'User'},
        ),
        migrations.AlterModelOptions(
            name='userinform',
            options={'verbose_name_plural': 'UserInform'},
        ),
        migrations.AlterField(
            model_name='userinform',
            name='status_message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
